name = "divortio-timeid-demo"
main = "src/worker.js"
compatibility_date = "2025-10-29"
workers_dev = false
preview_urls = false

# Serve the root directory (where index.html lives) as static assets
[assets]
directory = "."
binding = "ASSETS"

# Deployment
[observability]
enabled = true
head_sampling_rate = 1

[placement]
mode = "smart"

[[routes]]
pattern = "time.divort.io"
custom_domain = true

compatibility_flags = ["nodejs_compat", "nodejs_als"]

minify = true
workers_dev = false
preview_urls = false
